### ISSUE TITLE
article title order

### ISSUE THREAD

**Issue by mark-conrad** [mark-conrad/worcester-house#2]
Current pattern is:

Blue/green bar around 1 inch high with article title and breadcrumb

Image 

article title repeated

text of article

(I don't think we are using multiple article forms on most sections which is probably sensible.)

I think we might want something like:

Blue/green bar around 1 cm with breadcrumb

Main article title

Image if selected

text of article

**Comment by zodus** [comment]
As requested, I removed the second title
