### ISSUE TITLE
quantities on Woocommerce orders are doubled

### ISSUE THREAD

**Issue by mark-conrad** [mark-conrad/worcester-house#6]
Felix - we are finding that when orders come through from Scenar site (not sure about Asyra) - the quantities on the order are double what the customer selected, though the paypal payments are calculated correctly.

**Comment by zodus** [comment]
Just checked scenarworld, I ordered 1 item, I paid 1 item and 1 item arrived in the db, exactly as expected. For some reason ASYRA doesn't even use the NVLogin plugin. Did someone removed it???

Please reopen issue and provide additional info for test scenario if you require further testing
